---
- name: authorized_key
  hosts: '{{ host }}'
  remote_user: '{{ user }}'
  gather_facts: false

  tasks:
    - name: auth
      authorized_key: user='{{ user }}' key='{{ lookup('file', '../.ssh/clu.pub') }}'